# Generated by Django 4.0.3 on 2022-04-22 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='loan',
            old_name='loanAmout',
            new_name='loanAmount',
        ),
        migrations.AddField(
            model_name='loan',
            name='confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
