# Generated by Django 4.0.3 on 2022-04-22 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bank_app', '0002_rename_loanamout_loan_loanamount_loan_confirmed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loan',
            name='bankAccount',
        ),
    ]
