# Generated by Django 4.0.3 on 2022-04-22 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bank_app', '0003_remove_loan_bankaccount'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Loan',
        ),
    ]
