# Generated by Django 4.0.3 on 2022-04-23 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank_app', '0003_loan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bank',
            name='bankCode',
            field=models.CharField(max_length=4),
        ),
    ]
