# Generated by Django 4.0.3 on 2022-05-04 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bank_app', '0006_automaticpayment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AutomaticPayment',
        ),
    ]
