# Generated by Django 4.0.3 on 2022-05-06 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank_app', '0009_remove_automaticpayment_repeat_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
