# Generated by Django 4.0.3 on 2022-05-06 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank_app', '0010_alter_loan_confirmed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='confirmed',
            field=models.CharField(default='undefined', max_length=100),
        ),
    ]
