# Generated by Django 4.0.3 on 2022-05-18 15:30

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bank_app', '0011_alter_loan_confirmed'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cardNumber', models.IntegerField()),
                ('initialBalance', models.IntegerField()),
                ('spentAmount', models.IntegerField()),
                ('expiryDate', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('cvvNumber', models.IntegerField()),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bank_app.customer')),
            ],
        ),
    ]
