# Generated by Django 4.0.3 on 2022-05-18 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank_app', '0013_alter_creditcard_expirydate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditcard',
            name='expiryDate',
            field=models.DateField(),
        ),
    ]
