# Generated by Django 4.0.3 on 2022-05-18 18:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bank_app', '0014_alter_creditcard_expirydate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditcard',
            name='expiryDate',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
    ]
