# Generated by Django 4.0.3 on 2022-05-18 19:19

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bank_app', '0015_alter_creditcard_expirydate'),
    ]

    operations = [
        migrations.CreateModel(
            name='CardMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField()),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('description', models.TextField()),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bank_app.creditcard')),
            ],
        ),
    ]
